export const mapearCategorias = {
  "Placas de Video": "placas",
  Notebooks: "notebooks",
  Mothers: "mother",
  Procesadores: "procesadores",
  "Memorias RAM": "ram",
  Almacenamiento: "almacenamiento",
  Refrigeración: "refrigeracion",
  Gabinetes: "gabinetes",
  Fuentes: "fuentes",
  Monitores: "monitores",
  Periféricos: "perifericos",
  "Sillas Gamers": "sillas",
  Conectividad: "conectividad",
  Todos: "",
};
